services:
  - type: web
    name: pacific-budget-tracker-app
    env: static
    buildCommand: npm run build
    staticPublishPath: build  # Ensure the React build output is published
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: REACT_APP_DEFAULTAUTH
        value: fake
      - key: REACT_APP_ENABLE_LOCAL_API
        value: 1
      - key: REACT_APP_API_URL
        value: https://budgettracker-api.onrender.com
      - key: REACT_APP_APIKEY
        value: ""
    routes:
      - type: rewrite
        source: /*  # Catch-all route
        destination: /index.html  # Ensure all React Router routes are handled by React
